"""
context/outline_schema.py — Pydantic schema for the Gemini-generated video outline.

This is the single source of truth for the outline structure shared by:
  - summarizer.py   (writes it)
  - session_store.py (stores it)
  - prompt_builder.py (reads it)
  - ai_turn.py       (reads it for progress tracking)

Design notes:
  - summary_text lives INSIDE VideoOutline (not a separate SessionContext field)
    to avoid two-source-of-truth drift.
  - event_id is a stable integer assigned by Gemini and used for progress tracking
    across turns. Progress tracking keys off event_id, NOT off keyword matching
    against AI reply text.
  - All list fields have default_factory=list so the schema degrades gracefully:
    if Gemini omits a section (e.g., no characters found), the session still proceeds.
"""
from __future__ import annotations

from pydantic import BaseModel, Field


class OutlinePart(BaseModel):
    """One logical section of the video."""
    part: int
    title: str
    start_time: str          # e.g. "00:00"
    end_time: str            # e.g. "02:30"
    summary_text: str        # human-readable summary of this part


class Character(BaseModel):
    """A named person or entity appearing in the video."""
    name: str
    role: str


class KeyEvent(BaseModel):
    """A significant situation or incident with a stable integer ID for progress tracking."""
    event_id: int
    time: str                                   # e.g. "01:15"
    description: str
    characters: list[str] = Field(default_factory=list)
    part: int                                   # which outline part this event belongs to


class VideoOutline(BaseModel):
    """
    Structured breakdown of a video's content, characters, and events.
    Generated by Gemini at ingest time.
    """
    title: str = Field(
        default="",
        description="A natural language, 4-10 word title summarizing the lesson or specific situation. No technical brackets, marketing hype, or generic terms."
    )
    summary_text: str
    parts: list[OutlinePart] = Field(default_factory=list)
    characters: list[Character] = Field(default_factory=list)
    key_events: list[KeyEvent] = Field(default_factory=list)

    def format_characters(self) -> str:
        if not self.characters:
            return "None identified."
        return ", ".join(f"{c.name} ({c.role})" for c in self.characters)

    def format_parts(self) -> str:
        if not self.parts:
            return "No parts identified."
        lines = []
        for p in self.parts:
            lines.append(
                f"  Part {p.part} [{p.start_time}–{p.end_time}]: {p.title} — {p.summary_text}"
            )
        return "\n".join(lines)

    def format_key_events(self) -> str:
        if not self.key_events:
            return "No key events identified."
        lines = []
        for e in self.key_events:
            chars = (", ".join(e.characters)) if e.characters else "—"
            lines.append(f"  [{e.time}] (Event #{e.event_id}, Part {e.part}) {e.description} | Characters: {chars}")
        return "\n".join(lines)
